using System;

namespace Nimbus.DatabaseStructures.Models;

public class Currency
{
    public long Id { get; set; } // seeded integers or autogenerated
    public long TenantId { get; set; }
    public Tenant Tenant { get; set; } = null!;
    
    public string Code { get; set; } = null!; // e.g. "USD", "EUR", "GBP"
    public string Symbol { get; set; } = null!; // e.g. "$", "€", "£"
    public decimal ExchangeRateToBase { get; set; } // GBP is base = 1.0, USD = 1.25, etc.
    public bool IsBaseCurrency { get; set; } // true if GBP (reporting currency)
    public bool IsActive { get; set; } = true;
}
